#!/usr/bin/env bash 

set -euo pipefail 

HOST_FILE="${XDG_RUNTIME_DIR:-$HOME}/nix_host"
host=${1:-$(cat "$HOST_FILE" 2>/dev/null)}

if [[ -z "$host" ]]; then
  read 'Set default host: ' host || return 1
  echo "$host" > "$HOST_FILE"
fi

cd ~/nixos
echo "Updating host: $host"
sudo nix flake update
sudo nixos-rebuild switch --flake ".#$host" --upgrade --no-reexec && \
echo "Update successful." || echo "Update failed."


